---
title: "cms_payments"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(bigrquery)
```

```{r}
# Set up your Google Cloud Platform project ID and dataset ID
project_id <- "dtc-de-course-375205"
dataset_id <- "dezoomproj"

# Authenticate with Google Cloud Platform
# This will prompt you to sign in to your Google account and grant access
bq_auth(path = "~/Downloads/dtc-de-course-375205-f9f4c07d3b0b.json")

# Construct the SQL query to fetch data from the table
table_id <- "your_table_id"
sql_query <- sprintf("SELECT * FROM `%s.%s.%s`", project_id, dataset_id, table_id)

# Execute the query and download the data into an R dataframe
data <- bq_table_download(bq_project_query(project_id, sql_query))

# Now you can work with the downloaded data as a regular R dataframe
head(data)
```

## Inputs and Outputs

You can embed Shiny inputs and outputs in your document. Outputs are automatically updated whenever inputs change.  This demonstrates how a standard R plot can be made interactive by wrapping it in the Shiny `renderPlot` function. The `selectInput` and `sliderInput` functions create the input widgets used to drive the plot.

```{r eruptions, echo=FALSE}
inputPanel(
  selectInput("n_breaks", label = "Number of bins:",
              choices = c(10, 20, 35, 50), selected = 20),
  
  sliderInput("bw_adjust", label = "Bandwidth adjustment:",
              min = 0.2, max = 2, value = 1, step = 0.2)
)

renderPlot({
  hist(faithful$eruptions, probability = TRUE, breaks = as.numeric(input$n_breaks),
       xlab = "Duration (minutes)", main = "Geyser eruption duration")
  
  dens <- density(faithful$eruptions, adjust = input$bw_adjust)
  lines(dens, col = "blue")
})
```
